config/routes.rb
Saladfu2::Application.routes.draw do


  get "dressing/dressing"
  get "toppings/topping"
  root 'salads#index'
  get 'search', to: 'salads#search'
  resources :salads, only: [:new, :create, :show]
  devise_for :users


end

app/models/salad.rb
class Salad < ActiveRecord::Base

  belongs_to :users
  has_many :toppingizations
  has_many :salad_toppings, through: :toppingizations

  validates :salad_name, :lettuce_type, :description, presence: true
  validates :description, length: { minimum: 20 }
  validates :salad_name, uniqueness: true

  def self.search_for(query)
    where('salad_name LIKE :search_query OR description LIKE :search_query OR lettuce_type LIKE :search_query', search_query: "%#{query}%")
  end

  mount_uploader :image, ImageUploader




end

app/models/salad_toppings.rb
class SaladToppings < ActiveRecord::Base
  has_many :toppingizations
  has_many :salads, through: :toppingizations

end

app/models/toppingization.rb
class Toppingization < ActiveRecord::Base

  belongs_to :salad
  belongs_to :salad_toppings

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :salads

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/salads_controller.rb
class SaladsController < ApplicationController

  before_filter :authenticate_user! #, :except => [:show, :index]

  def index
    @salads = Salad.all
  end

  def new
    @salad = Salad.new

  end

  def create
    salad_params = params.require(:salad).permit(:salad_name, :description, :lettuce_type, :user_id, :user_name, :image, :cheese)
    @salad = Salad.new(salad_params)
    if @salad.save
      redirect_to @salad
    else
      render 'new'
    end
  end

  def show
    @salad = Salad.find(params[:id])
  end

  def search
    query = params[:q]
    @salads = Salad.search_for query
  end

  def edit
    @salad = Salad.find(params[:id])
  end



  def update

    @salad = Salad.find(params[:id])

    if @salad.update(params[:salad].permit(:salad_name, :description, :lettuce_type, :user_id, :user_name, :image))
      redirect_to @salad
    else
      render 'edit'
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salads_helper.rb
module SaladsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>


    <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1><%= link_to "Salad Fu", root_path %></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class="divider"></li>
        <li class="divider"></li>
        <li class="active"><a href="#"><%= link_to "", root_path %></a></li>
        </li>
        <li class="divider"></li>
      </ul>

      <!-- Right Nav Section    -->
      <ul class="right">
        <li class="divider hide-for-small"></li>
        <li class="active"><a href="#"><%= link_to "Home", root_path %></a></li>
        <li class="divider"></li>
        <li class="has-form">
          <form>
            <div class="row collapse">
            </div>
          </form>
        </li>
        <li class="divider show-for-small"></li>
      </ul>
    </section>
  </nav>






      <% if user_signed_in? %>
          <p>You are currently logged in as: <%= current_user.email %> | <%= link_to "Edit your account", edit_user_registration_path %> | <%= link_to "Go to salads", root_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
      <% else %>
          <%= link_to "Sign Up!", new_user_registration_path %> | <%= link_to "Sign In!", new_user_session_path %>
      <% end %>





    <%= yield %>


    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application_bak.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saladfu2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= form_tag 'search', method: :get do %>
    <%= label_tag :q, "Search" %>
    <%= search_field_tag :q, "", placeholder: 'Search' %>
    <%= submit_tag "Search" %>

<% end %>


<% if user_signed_in? %>
    <p>You are currently logged in as <%= current_user.email %>. | <%= link_to "Go to salads", salads_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
<% else %>
    <%= link_to "Sign Up!", new_user_registration_path %> | <%= link_to "Sign In!", new_user_session_path %>
<% end %>


<%= yield %>

</body>
</html>

app/views/salads/_list.html.erb
  <% @salads.each do |salad| %>




      <ul>
        <div class="small-6 large-2 columns"></div>
        <div class="small-6 large-8 columns">
          <b><%= salad.salad_name %></b> | Base: <%= salad.lettuce_type %><br>
          Description:<em> <%= salad.description %></em><br>
          <% if salad.cheese == true %>
              cheese
          <% end %></div>
        <div class="small-12 large-2 columns"</div>
      </div>



  <% end %>

app/views/salads/edit.html.erb
<h1>Salad Edit</h1>
<%= form_for :salad, url: salad_path(@salad.id), method: :patch do |f| %>




<% if @salad.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@salad.errors.count, "error") %> prohibited
        this salad from being saved:</h2>
      <ul>
        <% @salad.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

    <li>
      <%= f.label :salad_name %>
      <%= f.text_field :salad_name %>
    </li>
    <li>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </li>
    <li>
      <%= f.label :lettuce_type %>
      <%= f.text_field :lettuce_type %>
    </li>

<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'Back', salads_path %>

<% end %>

app/views/salads/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="description" content="Salad Fu">
  <meta name="keywords" content="">
  <title>Salad Fu</title>
</head>


<body>
<% content_for :title, "Salad Fu :: Home" %>


<div class="row">
  <div class="large-2 columns"></div>
  <div class="large-8 columns"><h1>Welcome To Salad Fu</h1></div>
  <div class="large-2 columns"></div>
</div>



<ul>
<%= form_tag 'search', method: :get do %>
<li><%= label_tag :q, "Search" %></li>
  <li><%= search_field_tag :q, "", placeholder: 'Search' %> </li>
  <li><%= submit_tag "Search" %>  </li>


</ul>
<% end %>
<h2><%= link_to 'New salad', new_salad_path %></h2>
    <div id="main_list">
       <%= render 'list' %>
    </div>



</body>
</html>

app/views/salads/new.html.erb
    <% if @salad.errors.any? %>


        The following errors prevented you from saving your salad:
        <ul>
          <% @salad.errors.full_messages.each do |error| %>
              <li>
                <%= error %>
              </li>
          <% end %>
        </ul>
    <% end %>

    <H1>Enter a new salad</H1>


      <%= form_for @salad do |f| %>

            <div class="row">    <div class="large-1 columns"></div>
            <div class="large-4 columns">
            <%= f.label :salad_name %></h4>

              <%= f.text_field :salad_name %></div>
            </div>

            <div class="row">
            <div class="large-4 columns">
              <h4 class="subheader"><%= f.label :description %>
            <%= f.text_field :description %></div>
            </div>

            <%= f.label :lettuce_type %>
            <%= f.text_field :lettuce_type %>

            <%= f.label :cheese %>
            <%= f.check_box :cheese %>


            <%= f.label :image %>
            <%= f.file_field :image %>

          <% current_user = @salad.user_name %>


            <h2><%= f.submit %> | <%= link_to 'Cancel', root_path %></h2>

         <% end %>

app/views/salads/search.html.erb
<h1>Search Results</h1>
<%= render 'list' %>
<%= link_to 'Back', :back %>

app/views/salads/show.html.erb
<h1>New salad created!</h1>

<h2><%= link_to 'Home', root_path %></h2>

<p>
    <%= @salad.salad_name %>
</p>
  <ul>
    <li><%= @salad.description %></li>
    <li><%= @salad.lettuce_type %></li>

    <% if @salad.cheese == true %>

        cheese

    <% end %>


    </li>



  </ul>